name: "🐛 Bug Report"
description: Report a bug or issue with the repository
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: dropdown
    id: type
    attributes:
      label: Bug Type
      description: What type of issue are you experiencing?
      options:
        - Broken link in README
        - Missing jobs that should appear
        - Duplicate job listings
        - Incorrect job information
        - Website issue (if applicable)
        - GitHub Actions failing
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug
      placeholder: Describe what's happening...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: Describe what you expected...

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information, screenshots, etc.
